// 1. Function to decode the Strava polyline into latitude/longitude points
const decodePolyline = (str, precision = 5) => {
    let index = 0, lat = 0, lng = 0, coordinates = [], shift = 0, result = 0, byte = null, latitude_change, longitude_change, factor = Math.pow(10, precision);
    while (index < str.length) {
        byte = null; shift = 0; result = 0;
        do { byte = str.charCodeAt(index++) - 63; result |= (byte & 0x1f) << shift; shift += 5; } while (byte >= 0x20);
        latitude_change = ((result & 1) ? ~(result >> 1) : (result >> 1));
        shift = result = 0;
        do { byte = str.charCodeAt(index++) - 63; result |= (byte & 0x1f) << shift; shift += 5; } while (byte >= 0x20);
        longitude_change = ((result & 1) ? ~(result >> 1) : (result >> 1));
        lat += latitude_change; lng += longitude_change;
        coordinates.push([lat / factor, lng / factor]);
    }
    return coordinates;
};

// 2. Main function to display activities and maps
const displayActivities = (activities) => {
    const container = document.getElementById('strava-data');
    container.innerHTML = ''; 

    activities.forEach(activity => {
        const distanceInMiles = (activity.distance * 0.000621371).toFixed(2);
        
        // Create a unique ID for each map so Leaflet knows where to draw
        const mapId = `map-${activity.id}`;
        
        const activityDiv = document.createElement('div');
        activityDiv.classList.add('activity');
        
        // Add the basic text AND a div to hold the map
        activityDiv.innerHTML = `
            <h3>${activity.name}</h3>
            <p><strong>Distance:</strong> ${distanceInMiles} miles</p>
            <p><strong>Pace:</strong> ${( (activity.moving_time / 60) / distanceInMiles ).toFixed(2)} min/mi</p>
            <div id="${mapId}" class="map-container"></div>
        `;
        
        container.appendChild(activityDiv);

        // 3. Draw the map using Leaflet
        if (activity.map && activity.map.summary_polyline) {
            const coordinates = decodePolyline(activity.map.summary_polyline);
            const map = L.map(mapId);
            
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; OpenStreetMap contributors'
            }).addTo(map);
            
            const polyline = L.polyline(coordinates, { color: '#fc4c02', weight: 4 }).addTo(map);
            map.fitBounds(polyline.getBounds());
        } else {
            document.getElementById(mapId).innerHTML = '<p><em>No GPS data for this activity.</em></p>';
            document.getElementById(mapId).style.height = 'auto';
        }
    });
};

// 4. Fetch data from the local file generated by GitHub Actions
fetch('activities.json')
.then(response => {
    if (!response.ok) {
        throw new Error('Network response was not ok');
    }
    return response.json();
})
.then(data => {
    // This is the function the script couldn't find earlier!
    displayActivities(data);
})
.catch(error => {
    console.error('Error fetching Strava data:', error);
    document.getElementById('strava-data').innerHTML = 'Failed to load activities.';
});